### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by apatlpo** [CNES/pangeo-pyinterp#1]
I cannot intall the library with:
```
(equinox) [pontea@visu03 drifters]$ conda install pangeo-pyinterp  -c fbriol
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pangeo-pyinterp

Current channels:
```

There seems to be a pyinterp library however:
```
(equinox) [pontea@visu03 drifters]$ conda search -c fbriol | grep pyinterp
pyinterp                  0.0.2  py37ha8d69ae_0  fbriol              
```

It this what should be used?

**Comment by fbriol** [comment]
I only made packages for Python 3.7. As you are trying to install the package for a version of Python that is not available, Conda tells you that it has not found anything. I just pushed a version for python 3.6. Let me know if you need another version.

**Comment by apatlpo** [comment]
3.6 but still not working.
I'm going to try switching to 3.7

**Comment by fbriol** [comment]
Without more information, I will not be able to reproduce it.... Here are the commands executed on a blank environment to test the package.

```bash
conda create --name py36 python=3.6
conda activate py36
conda install pyinterp -c fbriol
```
```python
import pyinterp.core
```

**Comment by fbriol** [comment]
Sorry I didn't read your problem correctly. You wrote:

```conda install pangeo-pyinterp -c fbriol```

When you have to write:

```conda install pyinterp -c fbriol```

**Comment by apatlpo** [comment]
ok, thanks, PR #2 underway
